### ISSUE TITLE
"Parameters vs. indices" side-note overflows

### ISSUE THREAD

**Issue by jskri** [jespercockx/agda-lecture-notes#12]
Thanks for your work!

agda.pdf (Version of March 20, 2023), page 11

The "Parameters vs. indices" side-note cannot be fully read as it goes beyond page bottom.

**Comment by jespercockx** [comment]
Thanks for letting me know, it's fixed in https://github.com/jespercockx/agda-lecture-notes/commit/bab756f553ba9c25209404406226e1f962bf8e8d
