### ISSUE TITLE
Exercise 2.6 needs to use "with" but that has not been taught, yet.

### ISSUE THREAD

**Issue by dimitri-xyz** [jespercockx/agda-lecture-notes#3]
Hi there,

This is an *excellent* tutorial on Agda, so I wanted to help out. I suggest modifying this exercise to only require going from `List'` to `List` (rather than both ways). Or removing it, as I believe `with` has not being introduced. I am a newbie here, so my apologies if this is not needed to complete the exercise.

https://github.com/jespercockx/agda-lecture-notes/blob/f3c8529504684a275b3cac569bea21b0476c1d3f/agda.lagda.tex#L1264

**Comment by jespercockx** [comment]
There's no need to use `with`, here is a possible solution that doesn't use it:
```agda
[]' : {A : Set} → List' A
[]' = 0 , []

_::'_ : {A : Set} → A → List' A → List' A
x ::' (n , xs) = suc n , x :: xs

from : {A : Set} → List A → List' A
from [] = []'
from (x :: xs) = x ::' from xs 

to : {A : Set} → List' A → List A
to (zero  , []       ) = []
to (suc n , (x :: xs)) = x :: to (n , xs)
```
I general, you can always avoid the use of `with` by defining an auxiliary function (though sometimes using `with` makes things quite a bit easier).

**Comment by jespercockx** [comment]
I've added an extra hint in https://github.com/jespercockx/agda-lecture-notes/commit/abb8bf496d07b55901824e23ab3b67cbb2c675d2.
