### ISSUE TITLE
Interactive programming giving different result for code snippet (25)

### ISSUE THREAD

**Issue by jmmarulang** [jespercockx/agda-lecture-notes#6]
o/

I have been following your tutorial and loving it so far. However, when trying to implement the `lookupVec` function from page 13 using interactive programming, Agda is giving me a different result. Was Agda updated? is this a bug? Am I just dumb?

# Steps to reproduce

Assuming you have been following the tutorial up to this point,

1. Add the following code to your .agda file.

```
lookupVec : {A : Set} → {n : Nat} → Vec A n → Fin n → A
lookupVec xs i = {!   !}
```

2.  Press Ctrl+c Ctrl+c and split on xs.

# Expected 

The tutorial shows the following code snippet (26)

```
lookupVec : {A : Set} → {n : Nat} → Vec A n → Fin n → A
lookupVec []         i = {!   !}
lookupVec (x :: xs) i = {!   !}
```
and its completed function is

```
lookupVec : {A : Set} → {n : Nat} → Vec A n → Fin n → A
lookupVec [] ()
lookupVec (x :: xs) zero = x
lookupVec (x :: xs) (suc i) = lookupVec xs i
```

# Actual 

```
lookupVec : {A : Set} → {n : Nat} → Vec A n → Fin n → A
lookupVec (x :: xs) i = {!   !}
```

And my completed function is

```
lookupVec : {A : Set} → {n : Nat} → Vec A n → Fin n → A
lookupVec (x :: xs) zero = x
lookupVec (x :: xs) (suc i) = lookupVec xs i
```

This code also compiles

# Tools used

Agda version 2.6.2.2

visual studio code

agda-mode v0.3.11 extension 

System type 64-bit operating system, x64-based processor

Edition Windows 10 Pro

Version 20H2

CC'ing @asr

**Comment by jespercockx** [comment]
Did you split first on `i` or first on `xs`? Depending on which variable you split on first, you might get a different result wrt absurd clauses. Since a few releases of Agda, absurd clauses are no longer mandatory in most cases.

**Comment by jmmarulang** [comment]
Thanks for your answer. I have experimented with both orders and the absurd clause does not appear. So perhaps its as you say.

**Comment by jespercockx** [comment]
You're correct, it seems something has changed in Agda since I wrote the text then. Thanks for notifying me, I'll update the text!
